url: https://oliver-be.ml/jekyll-lens/ 

## Site Meta ##
# The title of the website.
title: "Future Obscura"
# The description of the website
description: "A look into a commune shaped by pandemic, uncertainty, and guidelines; an examination of the ways in which we grow closer to one another in times of apartness."
# Keywords/tags for you site.
keywords: "lens, jeykll-lens, jekyll, theme, jekyll-theme, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Copyright &copy; 2021 - Oliver Baldwin Edwards"

## Site Configurations ##
# 1st heading of the site.
header: "Future Obscura"
# 2nd heading/sub heading of the website.
subheader: "Oliver Baldwin Edwards"
# A description/bio of the website.
bio: "A look into a commune shaped by pandemic, uncertainty, and guidelines; an examination of the ways in which we grow closer to one another in times of apartness."
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.s
  instagram_username: ""
  # GitHub username.
  github_username: ""
  # Your email address.
  email: "obaldwinedwards21@amherst.edu"
  # link to the project PDF
  project_pdf: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true

# set up the _photos collection
collections:
  photos: